# Generated by Django 2.1 on 2018-09-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rel_gov',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='rel_inv',
            field=models.IntegerField(default=75, verbose_name='Relacionamento com os investidores'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rel_pub',
            field=models.IntegerField(default=75, verbose_name='Relacionamento com o publico'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rel_trab',
            field=models.IntegerField(default=75, verbose_name='Relacionamento com os trabalhadores'),
        ),
    ]
