# Generated by Django 2.1 on 2018-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_principal', '0002_auto_20180916_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='lucro',
            field=models.IntegerField(default=1000000),
        ),
    ]
