# Generated by Django 2.1 on 2018-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_principal', '0003_usuarios_lucro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='lucro',
            new_name='producao',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='gastos',
            field=models.IntegerField(default=100000),
        ),
    ]
