# Generated by Django 2.1 on 2018-11-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tela_principal', '0007_usuarios_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='perdeu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='disciplina',
            field=models.IntegerField(default=50, verbose_name='Senso de disciplina'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='limpeza',
            field=models.IntegerField(default=50, verbose_name='Senso de limpeza'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='organizacao',
            field=models.IntegerField(default=50, verbose_name='Senso de organização'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='saude',
            field=models.IntegerField(default=50, verbose_name='Senso de saude'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='utilizacao',
            field=models.IntegerField(default=50, verbose_name='Senso de utilização'),
        ),
    ]
