# Generated by Django 2.1 on 2018-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('senha', models.CharField(max_length=20)),
                ('rel_gov', models.IntegerField(default=0, verbose_name='Relacionamento com o governo')),
                ('rel_pub', models.IntegerField(default=0, verbose_name='Relacionamento com o publico')),
                ('rel_trab', models.IntegerField(default=0, verbose_name='Relacionamento com os trabalhadores')),
                ('ult_alt', models.CharField(default='none', max_length=500, verbose_name='Ultima alteração')),
            ],
        ),
    ]
