# Generated by Django 2.1 on 2018-09-08 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(max_length=2000)),
                ('rel_gov', models.IntegerField(default=0, verbose_name='Relacionamento com o governo')),
                ('rel_pub', models.IntegerField(default=0, verbose_name='Relacionamento com o publico')),
                ('rel_trab', models.IntegerField(default=0, verbose_name='Relacionamento com os funcionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.CharField(max_length=2000)),
                ('aumenta', models.CharField(max_length=100)),
                ('diminui', models.CharField(max_length=100)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pergunta.Pergunta')),
            ],
        ),
    ]
