# Generated by Django 2.1 on 2018-09-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='rel_gov',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='ordem',
            field=models.CharField(default='random', max_length=9, verbose_name='Ordem da pergunta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='rel_inv',
            field=models.IntegerField(default=75, verbose_name='Relacionamento com os investidores'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='repete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='rel_pub',
            field=models.IntegerField(default=75, verbose_name='Relacionamento com o publico'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='rel_trab',
            field=models.IntegerField(default=75, verbose_name='Relacionamento com os funcionarios'),
        ),
    ]
