# Generated by Django 2.1.1 on 2018-09-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0002_auto_20180916_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='rel_inv',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='rel_pub',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='rel_trab',
        ),
        migrations.AddField(
            model_name='pergunta',
            name='disciplina',
            field=models.IntegerField(default=75, verbose_name='Senso de disciplina'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='limpeza',
            field=models.IntegerField(default=75, verbose_name='Senso de limpeza'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='organizacao',
            field=models.IntegerField(default=75, verbose_name='Senso de organização'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='saude',
            field=models.IntegerField(default=75, verbose_name='Senso de saúde'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='utilizacao',
            field=models.IntegerField(default=75, verbose_name='Senso de utilização'),
        ),
    ]
