# Generated by Django 2.1 on 2018-10-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0004_remove_pergunta_repete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='limpeza',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='organizacao',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='saude',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='utilizacao',
        ),
    ]
